plugins {
    id 'java'
    id 'com.adarshr.test-logger' version '3.1.0'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation 'junit:junit:4.+'
	testImplementation 'org.mockito:mockito-core:1.9.5'
}

testlogger {
    theme 'mocha'
    showExceptions true
    showStackTraces true
    showFullStackTraces false
    showCauses true
    slowThreshold 2000
    showSummary true
    showSimpleNames true
    showPassed true
    showSkipped true
    showFailed true
    showStandardStreams false
    showPassedStandardStreams true
    showSkippedStandardStreams true
    showFailedStandardStreams true
    logLevel 'lifecycle'
}